#!/bin/bash

if [[ -d /etc/fastapi-dls ]]; then
  echo "> Config directory not empty, please remove manually."
  # rm -r /etc/fastapi-dls
fi

if [[ -f /etc/systemd/system/fastapi-dls.service ]]; then
  echo "> Removing service file."
  rm /etc/systemd/system/fastapi-dls.service
fi

# todo
