#!/bin/bash

if [ -f /etc/systemd/system/fastapi-dls.service ]; then
  echo "> Removing service file."
  rm /etc/systemd/system/fastapi-dls.service
fi

if [ -d /usr/share/fastapi-dls ]; then
  echo "> Removing app."
  rm -r /usr/share/fastapi-dls
fi

# todo
